name: Build

on: [push]

env:
  AZURE_WEBAPP_NAME: filc-naplo    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd frontend && npm install
      - run: cd frontend && npm i @vue/cli-service
      - name: build
        run: cd frontend && npm run build
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader --no-dev
      - name: Generate key
        run: |
          php artisan key:generate
          php artisan jwt:secret
      - name: Optimize cache
        run: php artisan config:cache
      - name: Remove unnecesary files
        run: |
          rm -rf node_modules
          rm -rf tests
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

