name: Laravel

on: [push]

jobs:
  vue-build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install frontend
      - name: build
        run: cd frontend && npm run build
  laravel-optimize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader --no-dev
    - name: Generate key
      run: php artisan key:generate
    - run: php artisan jwt:secret
    - name: Optimize cache
      run: php artisan config:cache
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: 'https://dev.azure.com/bru02/MyProject'
          azure-pipeline-name: 'filc-naplo' # name of the Azure pipeline to be triggered
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
    

